-- Flyway가 앱 부팅 시 자동 실행. Hibernate는 ddl-auto=validate라 이 스키마와 엔티티가 일치해야 부팅된다.

CREATE TABLE members (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toss_user_key  BIGINT       NOT NULL UNIQUE,
    nickname       VARCHAR(50),
    created_at     TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE trips (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                  BIGINT           NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    destination                VARCHAR(100)     NOT NULL,
    start_date                 DATE             NOT NULL,
    end_date                   DATE             NOT NULL,
    travel_tip                 VARCHAR(500),
    temperature_min            DOUBLE PRECISION,
    temperature_max            DOUBLE PRECISION,
    precipitation_probability  INTEGER,
    temperature_perceived      DOUBLE PRECISION,
    created_at                 TIMESTAMP        NOT NULL DEFAULT now()
);
CREATE INDEX idx_trips_member_id ON trips(member_id);

CREATE TABLE trip_activities (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id        BIGINT      NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    activity_type  VARCHAR(20) NOT NULL
        CHECK (activity_type IN ('SWIMMING','CAMPING','HIKING','SIGHTSEEING','SHOPPING','FOOD_TOUR','RELAXING'))
);
CREATE INDEX idx_trip_activities_trip_id ON trip_activities(trip_id);

CREATE TABLE packing_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id     BIGINT       NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    name        VARCHAR(100) NOT NULL,
    category    VARCHAR(20)  NOT NULL
        CHECK (category IN ('CLOTHING','TOILETRIES','ELECTRONICS','DOCUMENTS','MEDICINE','GEAR','ETC')),
    reason      VARCHAR(255),
    checked     BOOLEAN      NOT NULL DEFAULT false,
    sort_order  SMALLINT     NOT NULL DEFAULT 0
);
CREATE INDEX idx_packing_items_trip_id ON packing_items(trip_id);
