-- 기존 service.SupportedRegions 정적 Map을 테이블로 이전.
-- region_name(한글 지역명)을 PK로, OpenWeatherMap 지오코딩 질의어를 값으로 저장한다.
-- "고성(강원)/고성(경남)", "광주/광주(경기)"처럼 동명 지역은 괄호로 구분한 별도 키로 등록한다.

CREATE TABLE supported_regions (
    region_name      VARCHAR(50)  PRIMARY KEY,
    geocoding_query  VARCHAR(100) NOT NULL
);

INSERT INTO supported_regions (region_name, geocoding_query) VALUES
    ('서울', 'Seoul,KR'),
    ('부산', 'Busan,KR'),
    ('대구', 'Daegu,KR'),
    ('인천', 'Incheon,KR'),
    ('광주', 'Gwangju,KR'),
    ('대전', 'Daejeon,KR'),
    ('울산', 'Ulsan,KR'),
    ('세종', 'Sejong,KR'),
    ('춘천', 'Chuncheon,KR'),
    ('원주', 'Wonju,KR'),
    ('강릉', 'Gangneung,KR'),
    ('속초', 'Sokcho,KR'),
    ('동해', 'Donghae,KR'),
    ('삼척', 'Samcheok,KR'),
    ('태백', 'Taebaek,KR'),
    ('정선', 'Jeongseon,KR'),
    ('평창', 'Pyeongchang-eup,KR'),
    ('홍천', 'Hongcheon,KR'),
    ('횡성', 'Hoengseong,KR'),
    ('영월', 'Yeongwol,KR'),
    ('인제', 'Inje,KR'),
    ('고성(강원)', 'Ganseong-eup,KR'),
    ('양양', 'Yangyang,KR'),
    ('철원', 'Cheorwon,KR'),
    ('청주', 'Cheongju,KR'),
    ('충주', 'Chungju,KR'),
    ('제천', 'Jecheon,KR'),
    ('단양', 'Danyang,KR'),
    ('보은', 'Boeun,KR'),
    ('옥천', 'Okcheon-eup,KR'),
    ('영동', 'Yeongdong-eup,KR'),
    ('진천', 'Jincheon,KR'),
    ('괴산', 'Goesan-eup,KR'),
    ('음성', 'Eumseong,KR'),
    ('천안', 'Cheonan,KR'),
    ('공주', 'Gongju,KR'),
    ('보령', 'Boryeong,KR'),
    ('아산', 'Asan,KR'),
    ('서산', 'Seosan,KR'),
    ('논산', 'Nonsan,KR'),
    ('계룡', 'Gyeryong,KR'),
    ('당진', 'Dangjin,KR'),
    ('태안', 'Taean,KR'),
    ('홍성', 'Hongseong,KR'),
    ('예산', 'Yesan,KR'),
    ('부여', 'Buyeo,KR'),
    ('서천', 'Seocheon-eup,KR'),
    ('청양', 'Cheongyang-eup,KR'),
    ('전주', 'Jeonju,KR'),
    ('군산', 'Gunsan,KR'),
    ('익산', 'Iksan,KR'),
    ('정읍', 'Jeongeup,KR'),
    ('남원', 'Namwon,KR'),
    ('김제', 'Gimje,KR'),
    ('완주', 'Samnye-eup,KR'),
    ('진안', 'Jinan-eup,KR'),
    ('무주', 'Muju,KR'),
    ('장수', 'Jangsu-eup,KR'),
    ('임실', 'Imsil,KR'),
    ('순창', 'Sunchang,KR'),
    ('고창', 'Gochang,KR'),
    ('부안', 'Buan-eup,KR'),
    ('목포', 'Mokpo,KR'),
    ('여수', 'Yeosu,KR'),
    ('순천', 'Suncheon,KR'),
    ('나주', 'Naju,KR'),
    ('광양', 'Gwangyang,KR'),
    ('담양', 'Damyang,KR'),
    ('곡성', 'Gokseong,KR'),
    ('구례', 'Gurye-eup,KR'),
    ('고흥', 'Goheung,KR'),
    ('보성', 'Boseong,KR'),
    ('화순', 'Hwasun,KR'),
    ('장흥', 'Jangheung-eup,KR'),
    ('강진', 'Gangjin,KR'),
    ('해남', 'Haenam,KR'),
    ('영암', 'Yeongam,KR'),
    ('무안', 'Muan-eup,KR'),
    ('함평', 'Hampyeong,KR'),
    ('영광', 'Yeonggwang,KR'),
    ('장성', 'Jangseong,KR'),
    ('완도', 'Wando,KR'),
    ('진도', 'Jindo,KR'),
    ('신안', 'Jido-eup,KR'),
    ('포항', 'Pohang,KR'),
    ('경주', 'Gyeongju,KR'),
    ('김천', 'Gimcheon,KR'),
    ('안동', 'Andong,KR'),
    ('구미', 'Gumi,KR'),
    ('영주', 'Yeongju,KR'),
    ('영천', 'Yeongcheon,KR'),
    ('상주', 'Sangju,KR'),
    ('문경', 'Mungyeong,KR'),
    ('경산', 'Gyeongsan,KR'),
    ('군위', 'Gunwi,KR'),
    ('의성', 'Uiseong,KR'),
    ('청송', 'Cheongsong-eup,KR'),
    ('영양', 'Yeongyang-eup,KR'),
    ('영덕', 'Yeongdeok,KR'),
    ('청도', 'Cheongdo-eup,KR'),
    ('고령', 'Daegaya-eup,KR'),
    ('성주', 'Seongju-eup,KR'),
    ('칠곡', 'Waegwan-eup,KR'),
    ('예천', 'Yecheon,KR'),
    ('봉화', 'Bonghwa-eup,KR'),
    ('울진', 'Uljin,KR'),
    ('울릉', 'Ulleung,KR'),
    ('창원', 'Changwon,KR'),
    ('진주', 'Jinju,KR'),
    ('통영', 'Tongyeong,KR'),
    ('사천', 'Sacheon,KR'),
    ('김해', 'Gimhae,KR'),
    ('밀양', 'Miryang,KR'),
    ('거제', 'Geoje,KR'),
    ('양산', 'Yangsan,KR'),
    ('의령', 'Uiryeong,KR'),
    ('함안', 'Haman,KR'),
    ('창녕', 'Changnyeong,KR'),
    ('고성(경남)', 'Goseong-eup,KR'),
    ('남해', 'Namhae,KR'),
    ('하동', 'Hadong-eup,KR'),
    ('산청', 'Sancheong,KR'),
    ('함양', 'Hamyang,KR'),
    ('거창', 'Geochang,KR'),
    ('합천', 'Hapcheon,KR'),
    ('제주', 'Jeju,KR'),
    ('서귀포', 'Seogwipo,KR'),
    ('수원', 'Suwon,KR'),
    ('성남', 'Seongnam,KR'),
    ('고양', 'Goyang,KR'),
    ('용인', 'Yongin,KR'),
    ('부천', 'Bucheon,KR'),
    ('안산', 'Ansan,KR'),
    ('안양', 'Anyang,KR'),
    ('남양주', 'Namyangju,KR'),
    ('화성', 'Hwaseong,KR'),
    ('평택', 'Pyeongtaek,KR'),
    ('파주', 'Paju,KR'),
    ('김포', 'Gimpo,KR'),
    ('이천', 'Icheon,KR'),
    ('가평', 'Gapyeong,KR'),
    ('양평', 'Yangpyeong,KR'),
    ('포천', 'Pocheon,KR'),
    ('연천', 'Yeoncheon,KR'),
    ('동두천', 'Dongducheon,KR'),
    ('의정부', 'Uijeongbu,KR'),
    ('광명', 'Gwangmyeong,KR'),
    ('시흥', 'Siheung,KR'),
    ('군포', 'Gunpo,KR'),
    ('오산', 'Osan,KR'),
    ('하남', 'Hanam,KR'),
    ('여주', 'Yeoju,KR'),
    ('광주(경기)', 'Gwangju-si,Gyeonggi-do,KR');
-- 해외 인기 여행지 90곳(아시아 30, 유럽 30, 아메리카 30)을 supported_regions 테이블에 추가.
-- region_name(한글 도시명)을 PK로, OpenWeatherMap 지오코딩 질의어(도시,국가코드)를 값으로 저장.
-- 국내 지역명과 중복되지 않는 해외 도시들로 구성.

INSERT INTO supported_regions (region_name, geocoding_query) VALUES
    -- ===== 아시아 (30) =====
    ('도쿄', 'Tokyo,JP'),
    ('오사카', 'Osaka,JP'),
    ('교토', 'Kyoto,JP'),
    ('삿포로', 'Sapporo,JP'),
    ('후쿠오카', 'Fukuoka,JP'),
    ('나고야', 'Nagoya,JP'),
    ('방콕', 'Bangkok,TH'),
    ('치앙마이', 'Chiang Mai,TH'),
    ('푸껫', 'Phuket,TH'),
    ('싱가포르', 'Singapore,SG'),
    ('홍콩', 'Hong Kong,HK'),
    ('마카오', 'Macau,MO'),
    ('타이베이', 'Taipei,TW'),
    ('가오슝', 'Kaohsiung,TW'),
    ('하노이', 'Hanoi,VN'),
    ('다낭', 'Da Nang,VN'),
    ('호치민', 'Ho Chi Minh City,VN'),
    ('발리', 'Denpasar,ID'),
    ('자카르타', 'Jakarta,ID'),
    ('쿠알라룸푸르', 'Kuala Lumpur,MY'),
    ('마닐라', 'Manila,PH'),
    ('세부', 'Cebu City,PH'),
    ('상하이', 'Shanghai,CN'),
    ('베이징', 'Beijing,CN'),
    ('시안', 'Xi''an,CN'),
    ('델리', 'Delhi,IN'),
    ('뭄바이', 'Mumbai,IN'),
    ('두바이', 'Dubai,AE'),
    ('프놈펜', 'Phnom Penh,KH'),
    ('시엠립', 'Siem Reap,KH'),
    -- ===== 유럽 (30) =====
    ('파리', 'Paris,FR'),
    ('니스', 'Nice,FR'),
    ('런던', 'London,GB'),
    ('에든버러', 'Edinburgh,GB'),
    ('로마', 'Rome,IT'),
    ('베네치아', 'Venice,IT'),
    ('피렌체', 'Florence,IT'),
    ('밀라노', 'Milan,IT'),
    ('나폴리', 'Naples,IT'),
    ('바르셀로나', 'Barcelona,ES'),
    ('마드리드', 'Madrid,ES'),
    ('세비야', 'Seville,ES'),
    ('리스본', 'Lisbon,PT'),
    ('포르투', 'Porto,PT'),
    ('암스테르담', 'Amsterdam,NL'),
    ('브뤼셀', 'Brussels,BE'),
    ('베를린', 'Berlin,DE'),
    ('뮌헨', 'Munich,DE'),
    ('프랑크푸르트', 'Frankfurt,DE'),
    ('프라하', 'Prague,CZ'),
    ('빈', 'Vienna,AT'),
    ('잘츠부르크', 'Salzburg,AT'),
    ('취리히', 'Zurich,CH'),
    ('인터라켄', 'Interlaken,CH'),
    ('부다페스트', 'Budapest,HU'),
    ('이스탄불', 'Istanbul,TR'),
    ('아테네', 'Athens,GR'),
    ('산토리니', 'Thira,GR'),
    ('코펜하겐', 'Copenhagen,DK'),
    ('스톡홀름', 'Stockholm,SE'),
    -- ===== 아메리카 (30) =====
    ('뉴욕', 'New York,US'),
    ('로스앤젤레스', 'Los Angeles,US'),
    ('라스베이거스', 'Las Vegas,US'),
    ('샌프란시스코', 'San Francisco,US'),
    ('시애틀', 'Seattle,US'),
    ('시카고', 'Chicago,US'),
    ('보스턴', 'Boston,US'),
    ('워싱턴', 'Washington,US'),
    ('마이애미', 'Miami,US'),
    ('올랜도', 'Orlando,US'),
    ('호놀룰루', 'Honolulu,US'),
    ('샌디에이고', 'San Diego,US'),
    ('뉴올리언스', 'New Orleans,US'),
    ('밴쿠버', 'Vancouver,CA'),
    ('토론토', 'Toronto,CA'),
    ('몬트리올', 'Montreal,CA'),
    ('멕시코시티', 'Mexico City,MX'),
    ('칸쿤', 'Cancun,MX'),
    ('과달라하라', 'Guadalajara,MX'),
    ('아바나', 'Havana,CU'),
    ('리우데자네이루', 'Rio de Janeiro,BR'),
    ('상파울루', 'Sao Paulo,BR'),
    ('부에노스아이레스', 'Buenos Aires,AR'),
    ('산티아고', 'Santiago,CL'),
    ('리마', 'Lima,PE'),
    ('쿠스코', 'Cusco,PE'),
    ('보고타', 'Bogota,CO'),
    ('카르타헤나', 'Cartagena,CO'),
    ('키토', 'Quito,EC'),
    ('라파스', 'La Paz,BO');
